In [2]:
%load_ext autoreload
%autoreload 2

In [38]:
import numpy as np
from tqdm import tqdm

from jaccard import *

In [4]:
np.set_printoptions(precision=4, suppress=True, floatmode='fixed')

In [131]:
m = 5
n = 15
avg_votes = 3
k = 2
V = np.random.choice([0, 1], (n, m), p=[1 - avg_votes / m, avg_votes / m])
print(V)

[[1 0 1 1 1]
 [0 1 1 1 1]
 [1 1 1 0 1]
 [1 1 1 1 1]
 [0 1 0 0 1]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [1 1 0 1 1]
 [1 0 0 1 0]
 [0 1 1 0 1]
 [0 0 1 1 1]
 [1 1 1 0 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [1 1 0 1 1]]


In [133]:
local_capture(V, k, 20)

potential results: 3003
potential results: 3003
potential results: 3003
potential results: 6435
potential results: 6435
potential results: 6435
potential results: 3003
potential results: 3003
potential results: 3003
potential results: 6435
potential results: 6435
potential results: 6435


(array([[0.4433, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 0.4433, 1.0000]]),
 1)

In [58]:
rho=1.125
counter={0: 4, 1: 4, 2: 2}
v=np.array([0, 1, 2, 3, 6])
centers=np.array([[0.4238, 1.0000, 1.0000],
       [0.0000, 0.9577, 0.9570]])
c=np.array([1.0000, 0.1916, 1.0000])
extended=np.array([[0.4238, 1.0000, 1.0000],
       [0.0000, 0.9577, 0.9570],
       [1.0000, 0.1916, 1.0000]])
jaccard(V, extended)

array([[0.5254, 0.6764, 0.0874],
       [0.1921, 0.3618, 0.2695],
       [0.1921, 0.3618, 0.2695],
       [0.1921, 0.3618, 0.2695],
       [0.1748, 0.0427, 0.6028],
       [0.5874, 0.5112, 0.5437],
       [0.5254, 0.6764, 0.0874],
       [0.5874, 0.5106, 0.9361],
       [0.5874, 0.5106, 0.9361],
       [0.1921, 0.3618, 0.2695]])

In [110]:
dist = jaccard_to_closest(V[v], centers)[0]
A, B, C, status = is_blocking_coalition(V[v], dist, rho)
assert status == 1
l = len(v)
print(V[v])
print(dist)
print(dist / rho)
print(jaccard_to_closest(V[v], centers)[0])
print(status)
A = [[value(a) for a in aa] for aa in A]
B = [[value(b) for b in bb] for bb in B]
C = [value(c) for c in C]
print(A)
print(B)
print(C)
for k, vv in enumerate(v):
    for i in range(m):
        assert A[k][i] <= C[i]
        assert A[k][i] <= V[vv][i]
        assert B[k][i] >= C[i]
        assert B[k][i] >= V[vv][i]
    assert sum(A[k]) >= (1 - (dist / rho)[k]) * sum(B[k]), f"{sum(A[k])} >= {(1 - dist[k] / rho) * sum(B[k])}"

a_0_0 + a_0_1 + a_0_2 - 0.5329777777777778*b_0_0 - 0.5329777777777778*b_0_1 - 0.5329777777777778*b_0_2 >= 1e-06
a_1_0 + a_1_1 + a_1_2 - 0.829274074074074*b_1_0 - 0.829274074074074*b_1_1 - 0.829274074074074*b_1_2 >= 1e-06
a_2_0 + a_2_1 + a_2_2 - 0.829274074074074*b_2_0 - 0.829274074074074*b_2_1 - 0.829274074074074*b_2_2 >= 1e-06
a_3_0 + a_3_1 + a_3_2 - 0.829274074074074*b_3_0 - 0.829274074074074*b_3_1 - 0.829274074074074*b_3_2 >= 1e-06
a_4_0 + a_4_1 + a_4_2 - 0.5329777777777778*b_4_0 - 0.5329777777777778*b_4_1 - 0.5329777777777778*b_4_2 >= 1e-06
[[1 0 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 0 1]]
[0.5254 0.1921 0.1921 0.1921 0.5254]
[0.4670 0.1707 0.1707 0.1707 0.4670]
[0.5254 0.1921 0.1921 0.1921 0.5254]
1
[[1.0, 0.0, 1.0], [1.0, 0.48782322, 1.0], [1.0, 0.48782322, 1.0], [1.0, 0.48782322, 1.0], [1.0, 0.0, 1.0]]
[[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
[1.0, 0.48782322, 1.0]
