In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from tqdm import tqdm

from jaccard import *

In [3]:
np.set_printoptions(precision=4, suppress=True, floatmode='fixed')

In [4]:
m = 3
n = 10
avg_votes = 2
projects_to_found = 2
V = np.random.choice([0, 1], (n, m), p=[1 - avg_votes / m, avg_votes / m])
print(V)

[[1 0 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]
 [1 1 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [110]:
A, B, C, dist = center(V)
centers = np.array([value(c) for c in C]).reshape(1, -1)

In [113]:
print(dist)
print([
    sum([value(A[k][i]) for i in range(2)]) / sum([value(B[k][i]) for i in range(2)])
    for k in range(2)
])
print(centers)

0.5657414263114333
[0.5000000400000032, 0.65138786]
[[1.0000 1.0000 0.3028]]


In [17]:
dist, _ = jaccard_to_closest(V, centers)
print(dist)

[0.5657 0.2324 0.5657 0.5657 0.2324 0.5657 0.5657 0.2324 0.5657 0.5657]


In [119]:
res = find_blocking_coalition(V, centers, size=n//2, rho=1.93)
print(res)

potential results: 21
(array([1, 2, 4, 7, 9]), array([0.4660, 1.0000, 1.0000]))
